apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.41.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: "/prometheus"
              name: storage-volume
      volumes:
        - name: storage-volume
          emptyDir: {}