kube-prometheus-stack:
  enabled: true
  fullnameOverride: prometheus

  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false

  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None