apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-tmp-pvc
  namespace: airflow  
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi  
  storageClassName: standard  