apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Thanabodin19/PYUI-GPT-Deploy
    targetRevision: main
    path: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
