apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyui-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Thanabodin19/Test-argucd-deploy.git
    targetRevision: main
    path: pyui-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
