apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Thanabodin19/PYUI-GPT-Infrastructure.git
    targetRevision: main
    path: charts/argocd
    helm:
      valueFiles:
        - charts/argocd/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
