apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Thanabodin19/PYUI-GPT-Infrastructure.git
    targetRevision: main
    path: charts/prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
