apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  #   - hosts:
  #     - {{ .Values.domain }}
  #     secretName: argocd-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443