apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'cert-manager-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Thanabodin19/PYUI-GPT-Infrastructure.git
        targetRevision: "main" #Based on environment
        path: 'addons/manifests/cert-manager'
      destination:
        name: in-cluster
        namespace: cert-manager
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true