apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki-log
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'loki-log-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Thanabodin19/PYUI-GPT-Infrastructure.git
        targetRevision: main #Based on environment
        path: 'addons/manifests/loki-log'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: loki-log
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true