kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pyui-gpt
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=control-plane-1"
    extraMounts:
      - hostPath: ./data/images
        containerPath: 
    extraPortMappings:
      - containerPort: 80  # Ingress HTTP
        hostPort: 8088
      - containerPort: 443  # Ingress HTTPS
        hostPort: 8443
      - containerPort: 30888  # NodePort สำหรับ WebApp
        hostPort: 8888

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker-1"
    extraMounts:
      - hostPath: ./data/images
        containerPath: 
